version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw
  
  db-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
