import "@fontsource/open-sans"
import "@fontsource/outfit"

import type { Metadata } from 'next'
import baseStyles from '~f/framework/base.module.scss'
import './global.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1 className={baseStyles.Heading__highlighted}>Cosmos Example Application</h1>
        {children}
      </body>
    </html>
  )
}
